#!/usr/bin/env python3
"""
Plot a confusion matrix from saved RAG accuracy test results.

Usage:
    python plot_confusion_matrix.py <results.json> [--output matrix.png] [--normalize]
"""

import argparse
import json
from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a confusion matrix figure from accuracy test JSON results."
    )
    parser.add_argument(
        "results_path",
        type=Path,
        help="Path to rag_accuracy_test_*.json file generated by the accuracy tester.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to save the confusion matrix figure (PNG). "
        "If omitted, the figure window is shown interactively.",
    )
    parser.add_argument(
        "--normalize",
        action="store_true",
        help="Normalize counts to percentages per actual class.",
    )
    return parser.parse_args()


def load_predictions(results_path: Path) -> Tuple[List[str], List[str]]:
    """Extract true/predicted case IDs from the JSON results file."""
    data = json.loads(results_path.read_text())
    entries = data.get("results", [])

    y_true: List[str] = []
    y_pred: List[str] = []

    for entry in entries:
        if not entry.get("success"):
            continue
        expected = entry.get("expected_case")
        sources = entry.get("sources") or []
        predicted = sources[0] if sources else None
        if expected and predicted:
            y_true.append(expected)
            y_pred.append(predicted)

    if not y_true:
        raise ValueError("No comparable predictions found in the results file.")

    return y_true, y_pred


def build_confusion_matrix(
    y_true: List[str], y_pred: List[str]
) -> Tuple[List[str], np.ndarray]:
    """Create a confusion matrix for the provided labels."""
    labels = sorted(set(y_true) | set(y_pred))
    label_to_idx = {label: idx for idx, label in enumerate(labels)}
    matrix = np.zeros((len(labels), len(labels)), dtype=float)

    for truth, pred in zip(y_true, y_pred):
        matrix[label_to_idx[truth], label_to_idx[pred]] += 1

    return labels, matrix


def normalize_matrix(matrix: np.ndarray) -> np.ndarray:
    """Normalize confusion matrix rows to sum to 1.0."""
    row_sums = matrix.sum(axis=1, keepdims=True)
    with np.errstate(divide="ignore", invalid="ignore"):
        normalized = np.divide(matrix, row_sums, where=row_sums != 0)
    normalized[np.isnan(normalized)] = 0.0
    return normalized


def plot_matrix(
    labels: List[str],
    matrix: np.ndarray,
    normalize: bool,
    output_path: Path | None,
) -> None:
    """Render the confusion matrix with matplotlib."""
    display_matrix = normalize_matrix(matrix) if normalize else matrix
    title_suffix = " (normalized)" if normalize else ""

    fig_width = max(6, len(labels) * 0.9)
    fig_height = max(5, len(labels) * 0.9)
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    cmap = plt.cm.Blues

    im = ax.imshow(display_matrix, interpolation="nearest", cmap=cmap)
    ax.figure.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    ax.set(
        xticks=np.arange(len(labels)),
        yticks=np.arange(len(labels)),
        xticklabels=labels,
        yticklabels=labels,
        ylabel="Actual case",
        xlabel="Predicted case",
        title=f"Confusion Matrix{title_suffix}",
    )
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")

    thresh = display_matrix.max() / 2 if display_matrix.size else 0
    for i in range(display_matrix.shape[0]):
        for j in range(display_matrix.shape[1]):
            value = display_matrix[i, j]
            text = f"{value:.2f}" if normalize else f"{int(value)}"
            ax.text(
                j,
                i,
                text,
                ha="center",
                va="center",
                color="white" if value > thresh else "black",
            )

    fig.tight_layout()

    if output_path:
        fig.savefig(output_path, dpi=300, bbox_inches="tight")
        print(f"✅ Confusion matrix saved to {output_path}")
    else:
        plt.show()


def main() -> None:
    args = parse_args()
    if not args.results_path.exists():
        raise FileNotFoundError(f"Results file not found: {args.results_path}")

    y_true, y_pred = load_predictions(args.results_path)
    labels, matrix = build_confusion_matrix(y_true, y_pred)
    plot_matrix(labels, matrix, args.normalize, args.output)


if __name__ == "__main__":
    main()
